name: Build Phantom

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pip install pyinstaller
      - run: pyinstaller phantom.spec
      - uses: actions/upload-artifact@v3
        with:
          name: Phantom-Windows
          path: dist/Phantom/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: sudo apt-get install -y libpcap-dev
      - run: pip install -r requirements.txt
      - run: pip install pyinstaller
      - run: pyinstaller phantom.spec
      - uses: actions/upload-artifact@v3
        with:
          name: Phantom-Linux
          path: dist/Phantom/